server:
  port: 8011

spring:
  main:
    allow-circular-references: true
  application:
    name: zuul-api-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    user-service:
      path: /users/**
      serviceId: USERS-WS
      stripPrefix: true

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

jwt:
  token:
    secret: 9Bx9iEbda6zPregfwb8jkgc9SQZwndLHz7ghybjuY24x4MC9CCAEtg3MndvJujdN

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace