server:
  port: 8011

spring:
  main:
    allow-circular-references: true
  application:
    name: zuul-api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    user-service:
      path: /users/**
      serviceId: USERS-WS