server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/sergey-microservices
#    username: root
#    password: pa55word
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


# port=0 olursa sistem tarafından otomatik port numarası verilerek uygulama ayağa kaldırılır.
# fakat birden fazla instance oluşturmak istendiğinde eureka üzerinde tek instance görülür çünkü port numarası elle setlenmiştir.
# Onun yerine instance id tanımlaması yapılmalıdır.